enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "both"
# excluded-patches = "'Hide shortcuts'"
# included-patches = "'Custom branding icon for YouTube', 'Custom branding name for YouTube', 'Custom header for youtube', 'Hide shorts dimming', 'Hide shortcuts', 'MaterialYou'"
# version = "auto"
# version = "19.44.39"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [Music]
# build-mode = "both"
# arch = "both"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

# [GooglePhotos]
# build-mode = "both"
# arch = "both"
# version = "auto"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
# uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

# dont build on gh actions (https://github.com/j-hc/revanced-magisk-module/issues/554)
# [Music-Extended]
# enabled = false
# app-name = "Music"
# patches-source = "anddea/revanced-patches"
# cli-source = "inotia00/revanced-cli"
# rv-brand = "ReVanced Extended"
# build-mode = "both"
# arch = "arm64-v8a"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "v3.15.0-dev.3"
rv-brand = "ReVanced Extended"
build-mode = "both"
version = "20.21.37"
# version = "auto"
# pather-args = "'-OsettingsMenuIcon=gear', '-OappIcon=youtube', '-OdarkThemeBackgroundColor=@android:color/black'"
# patcher-args = "--legacy-options options.json"
# patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon='mmt' -e 'Snack bar components' -OdarkThemeBackgroundColor='@android:color/black'"
included-patches = """\
'Custom header for YouTube' \
'Hide Shorts dimming' \
'Hide shortcuts' \
'MaterialYou' \
"""
excluded-patches = """\
'Hide shortcuts'\
'Custom branding icon for YouTube' \
'Custom branding name for YouTube' \
'Disable layout updates' \
"""
patcher-args = "-e 'Visual preferences icons for YouTube' -OsettingsMenuIcon=gear -e 'Settings for YouTube' -OrvxSettingsLabel='ReVanced Extended' -e 'Snackbar components' -OdarkThemeBackgroundColor=@android:color/black"
arch = "arm64-v8a"
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Extended]
enabled = true
app-name = "YouTube Music"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "v3.15.0-dev.3"
rv-brand = "ReVanced Extended"
build-mode = "both"
version = "8.30.54"
included-patches = """\
'Custom header for YouTube Music' \
'Disable music video in album' \
'Hide overlay filter' \
'Hide player overlay filter' \
"""
excluded-patches = """\
'Dark theme' \
'Custom branding name for YouTube Music' \
"""
patcher-args = "-e 'Visual preferences icons for YouTube Music' -OsettingsMenuIcon=gear -e 'Settings for YouTube Music' -OrvxSettingsLabel='ReVanced Extended'"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[Spotify]
enabled = false
app-name = "Spotify"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "v3.12.0-dev.9"
rv-brand = "ReVanced Extended"
build-mode = "apk"
version = "latest"
excluded-patches = """\
'Change lyrics provider' \
'Custom branding name for Spotify' \
'Custom theme' \
'Hide Create button' \
'Unlock Premium' \
"""
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[Twitter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
enabled = false
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

# [Spotify]
# enabled = false
# uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
